<?php /** @var Magento\Framework\View\Element\Template $block */ ?>
<?php /** @var Bazaarvoice\Connector\ViewModel\Header $viewModel */ ?>
<?php $viewModel = $block->getViewModel(); ?>

<?php if ($viewModel->isBvEnabled()): ?>
    <?php $bvApiUrl = $viewModel->getConfigProvider()->getBvApiHostUrl(); ?>
    <!--suppress HtmlUnknownTarget -->
    <script async type="text/javascript" src="<?= $bvApiUrl; ?>"></script>
<?php endif; ?>
