<?php /** @var Bazaarvoice\Connector\Block\Product $this */ ?>

<?php if ($this->isEnabled()) : ?>
<?php if ($this->isConfigurable() && $this->getConfig( 'rr/children' )) : ?>
    <script type="text/javascript">
        var bvChildren = <?php echo $this->getChildrenJson(); ?>;
        var bvSelected = "<?php echo $this->getProductSku() ?>";
        require(["jquery"], function ($) {
            function bindBvSwatches() {
                $('#product-options-wrapper').on('click', '.swatch-option', function () {
                    var bvCurrent = '';
                    $('.swatch-attribute').each(function () {
                        bvCurrent = bvCurrent
                            + $(this).attr('attribute-id') + '_'
                            + $(this).attr('option-selected') + '_';
                    });
                    console.log(bvCurrent);
                    if (bvChildren[bvCurrent] != undefined && bvChildren[bvCurrent] != bvSelected) {
                        var externalId = bvChildren[bvCurrent];
                        console.log("switching to " + externalId);
                        bvSelected = bvChildren[bvCurrent];
                        $('div[data-bv-show=reviews]').attr('data-bv-product-id', externalId)
                        BV.reviews.render($('div[data-bv-show=reviews]')[0]);
                        $('div[data-bv-show=questions]').attr('data-bv-product-id', externalId)
                        BV.questions.render($('div[data-bv-show=questions]')[0]);
                        $('div[data-bv-show=rating_summary]').attr('data-bv-product-id', externalId)
                        BV.rating_summary.render($('div[data-bv-show=rating_summary]')[0]);
                    }
                });
            }

                $(document).ready(bindBvSwatches());
            });
        </script>
    <?php endif; ?>
    <?php
    $rrDoShowContentJs = $this->getConfig( 'rr/do_show_content_js' );
    $qaDoShowContentJs = $this->getConfig( 'qa/do_show_content_js' );

    $configData = $this->getBvConfigData();
    ?>
    <!-- <?php print_r( json_decode( $configData ) ) ?> -->

    <script async type="text/javascript">

        window.bvDCC = {
            catalogData: {
                locale: "<?php echo $this->getConfig( 'general/locale' ) ?>",
                catalogProducts: <?php echo $configData ?>
            }
        };

        const eventClass = "CatalogUpdate";

        window.bvCallback = function (BV) {
            BV.reviews.on('show', function () {
                <?php echo $rrDoShowContentJs ?>
            });
            BV.questions.on('show', function () {
                <?php echo $qaDoShowContentJs ?>
            });

            for (var i = 0, len = window.bvDCC.catalogData.catalogProducts.length; i < len; ++i) {
                BV.pixel.trackEvent(eventClass, {
                    type: 'Product',
                    locale: window.bvDCC.catalogData.locale,
                    catalogProducts: [window.bvDCC.catalogData.catalogProducts[i]]
                });
            }
        };


    </script>
<?php endif; ?>
