<?php
/**
 * StoreFront Bazaarvoice Extension for Magento
 *
 * PHP Version 5
 *
 * LICENSE: This source file is subject to commercial source code license
 * of StoreFront Consulting, Inc.
 *
 * @category  SFC
 * @package   Bazaarvoice_Ext
 * @author    Dennis Rogers <dennis@storefrontconsulting.com>
 * @copyright 2016 StoreFront Consulting, Inc
 * @license   http://www.storefrontconsulting.com/media/downloads/ExtensionLicense.pdf StoreFront Consulting Commercial License
 * @link      http://www.StoreFrontConsulting.com/bazaarvoice-extension/
 */
?>
<?php /** @var Bazaarvoice\Connector\Block\Product $this */ ?>

<?php /* if ($this->isEnabled()): ?>
    <!--suppress ALL -->
    <script type="text/javascript">
        var bvConfigData = {};
<?php if ($this->getProductId()) : ?>
        bvConfigData.productId = "<?php echo $this->getProductSku() ?>";
<?php endif; ?>
        $BV.configure("global", bvConfigData);
    </script>
<?php if ($this->isConfigurable()): ?>
    <script type="text/javascript">
        var bvChildren = <?php echo $this->getChildrenJson(); ?>;
        var bvSelected = "<?php echo $this->getProductSku() ?>";
        require(["jquery", "jquery/ui", "swatchRenderer"], function ($) {

            jQuery('.swatch-option').live("mouseout", function(){
                var bvCurrent = '';
                jQuery('.swatch-attribute').each(function(){
                    bvCurrent = bvCurrent + jQuery(this).attr('attribute-id') + '_' + jQuery(this).attr('option-selected') + '_';
                });
                console.log(bvCurrent);
                if (bvChildren[bvCurrent] != undefined && bvChildren[bvCurrent] != bvSelected) {
                    console.log("switching to " + bvChildren[bvCurrent]);
                    bvConfigData.productId = bvChildren[bvCurrent];
                    $BV.configure("global", bvConfigData);
                    $BV.ui( 'rr', 'show_reviews', {
                        doShowContent : function () {
                            <?php echo $this->getConfig('rr/do_show_content_js'); ?>
                        }
                    });
                    bvSelected = bvChildren[bvCurrent];
                }
            });

        });
    </script>
<?php endif; ?>
    
<?php endif; */ ?>
<?php
$rrDoShowContentJs = $this->getConfig('rr/do_show_content_js');
$qaDoShowContentJs = $this->getConfig('qa/do_show_content_js');
?>

<script async type="text/javascript">
    window.bvCallback = function (BV) {
        BV.reviews.on('show', function () {
            <?php echo $rrDoShowContentJs ?>
        });
        BV.questions.on('show', function () {
            <?php echo $qaDoShowContentJs ?>
        });
    };
</script>
