<?php
/**
 * Copyright © Bazaarvoice, Inc. All rights reserved.
 * See LICENSE.md for license details.
 */
?>

<?php /** @var Magento\Framework\View\Element\Template $block */ ?>
<?php /** @var Bazaarvoice\Connector\ViewModel\Reviews $viewModel */ ?>
<?php $viewModel = $block->getViewModel(); ?>

<?php if ($viewModel->canShow()) : ?>
    <!-- <?= $viewModel->getExtensionInjectionMessage(); ?> -->
    <?php $seoContent = $viewModel->getSeoContent(); ?>
    <div data-bv-show="reviews" data-bv-product-id="<?= $viewModel->getProductSku() ?>">
        <?= $seoContent ?>
    </div>
<?php endif;



