<?php /**
 * StoreFront Bazaarvoice Extension for Magento
 *
 * PHP Version 5
 *
 * LICENSE: This source file is subject to commercial source code license
 * of StoreFront Consulting, Inc.
 *
 * @category  SFC
 * @package   Bazaarvoice_Ext
 * @author    Dennis Rogers <dennis@storefrontconsulting.com>
 * @copyright 2016 StoreFront Consulting, Inc
 * @license   http://www.storefrontconsulting.com/media/downloads/ExtensionLicense.pdf StoreFront Consulting Commercial License
 * @link      http://www.StoreFrontConsulting.com/bazaarvoice-extension/
 */ ?>
<?php /** @var \Bazaarvoice\Connector\Block\Reviews $this */ ?>
<?php if ($this->isEnabled()): ?>
    <!-- foo -->
<div id="BVRRSummaryContainer" style="display:table-row"><?php echo $this->getAggregateSEOContent() ?></div>
<?php endif;