<?php /** @var Magento\Framework\View\Element\Template $block */ ?>
<?php /** @var Bazaarvoice\Connector\ViewModel\Reviews $viewModel */ ?>
<?php $viewModel = $block->getViewModel(); ?>

<?php if ($viewModel->canShow()) : ?>
    <div data-bv-show="rating_summary"
         data-bv-product-id="<?= $viewModel->getProductSku() ?>">
        <?= $viewModel->getAggregateSEOContent() ?>
    </div>
<?php endif;
/**
 * Copyright © Bazaarvoice, Inc. All rights reserved.
 * See LICENSE.md for license details.
 */


