<?php
/**
 * Copyright © Bazaarvoice, Inc. All rights reserved.
 * See LICENSE.md for license details.
 */
?>

<?php /** @var Magento\Framework\View\Element\Template $block */ ?>
<?php /** @var Bazaarvoice\Connector\ViewModel\Reviews $viewModel */ ?>
<?php $viewModel = $block->getViewModel(); ?>

<?php if ($viewModel->canShow()): ?>
    <!-- <?= $escaper->escapeHtml($viewModel->getExtensionInjectionMessage()); ?> -->
    <div data-bv-show="rating_summary"
         data-bv-product-id="<?= $escaper->escapeHtml($viewModel->getProductSku()) ?>">
        <?= $escaper->escapeHtml($viewModel->getAggregateSEOContent()) ?>
    </div>
<?php endif;

