
<?php if($this->isEnabled()): ?>

    <?php if($this->getProductId()) : ?>

        <script type="text/javascript">
        $BV.configure('global', { productId : "<?php echo $this->getProductSku() ?>" });
        </script>

    <?php else: ?>
    
        <script type="text/javascript" language="javascript">
        <?php // Comment out extra features until we know we need them ?>
        <?php //var profileDisplayContainerPageName = "bazaarvoice/profile/display"; ?>
        var configData = {};
        <?php /* if (false) { //!empty($submissionContainerUrl)) {
                    echo "    configData.submissionContainerUrl = \"".$submissionContainerUrl."\";\n";
                }
        */ ?>
        $BV.configure("global", configData);
        </script>
    
    <?php endif; ?>

<?php endif; ?>