<?php /** @var Magento\Framework\View\Element\Template $block */ ?>
<?php /** @var Bazaarvoice\Connector\ViewModel\Pixel $viewModel */ ?>
<?php $viewModel = $block->getViewModel(); ?>

<?php if ($viewModel->getBvPixelEnabled()) : ?>
    <?php if ($viewModel->canShowDebugDetails()) : ?>
        <!--<?= $viewModel->getDebugDetails(); ?>-->
    <?php endif; ?>
    <script type="text/javascript">
        var transactionData = <?= $viewModel->getJsonOrderDetails(); ?>;
        window.bvCallback = function (BV) {
            BV.pixel.trackTransaction(transactionData);
        }
    </script>
<?php endif; ?>
