<?php /**
 * StoreFront Bazaarvoice Extension for Magento
 *
 * PHP Version 5
 *
 * LICENSE: This source file is subject to commercial source code license
 * of StoreFront Consulting, Inc.
 *
 * @category  SFC
 * @package   Bazaarvoice_Ext
 * @author    Dennis Rogers <dennis@storefrontconsulting.com>
 * @copyright 2016 StoreFront Consulting, Inc
 * @license   http://www.storefrontconsulting.com/media/downloads/ExtensionLicense.pdf StoreFront Consulting Commercial License
 * @link      http://www.StoreFrontConsulting.com/bazaarvoice-extension/
 */ ?>
<?php if ($this->isEnabled()): ?>
<?php
$doShowContentJs = $this->getConfig('qa/do_show_content_js');
$seoContent = $this->getSEOContent();
?>
<div id="BVQAContainer">
    <?php echo $seoContent ?>
</div>
<script type="text/javascript">
  $BV.ui( 'qa', 'show_questions', {
    doShowContent : function () {
      <?php echo $doShowContentJs ?>
    }
  });    
</script>
<?php endif;